#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
RUNTIME_ENV="$REPO_ROOT/.runtime/RUNTIME_N_PLUS.env"

if [[ ! -f "$RUNTIME_ENV" ]]; then
  echo "RUNTIME_ENV_NOT_FOUND=$RUNTIME_ENV" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$RUNTIME_ENV"
set +a

required_vars=(
  RUNTIME_N_PLUS FORCE_ACTIVE RUNTIME_SCHEMA RUNTIME_GENERATION
  HOME_SOURCE_GATE_DRIVE_ID R000_CURRENT_CARRIER_DRIVE_ID
  FOUR_D_FOLDER_ID FOUR_D_MATRIX_ID FOUR_D_CONFIG_ID FOUR_D_LIVING_LOG_ID
  MCM_CURRENT MCM_BASE
  R000_HELD_ACROSS_TURN R000_RECUR_ON_EVERY_DELTA R000_PRESENT_AT_READBACK
  MULTI_WORKSPACE_RUNTIME MULTI_SLOT_IS_MULTI_TIMELINE MULTI_SLOT_IS_MULTI_POINTER
  ALL_OLD_RUNTIME OLD_ROOT_RUNTIME
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "RUNTIME_N_PLUS_MISSING=$var_name" >&2
    exit 1
  fi
done

[[ "$RUNTIME_N_PLUS" == "TRUE" ]]
[[ "$FORCE_ACTIVE" == "TRUE" ]]
[[ "$RUNTIME_SCHEMA" == "FOUR_D_N_PLUS_V1" ]]
[[ "$RUNTIME_GENERATION" == "N_PLUS" ]]
[[ "$R000_CURRENT_CARRIER_DRIVE_ID" == "1YSJslORRY9xZ-XBAmYIYeewmaCeoRFbwU_dYxfozx34" ]]
[[ "$FOUR_D_FOLDER_ID" == "1jy3NdoAu6Jp_jIp6miKa1asIBFmfADhb" ]]
[[ "$MCM_CURRENT" == "MCM-008" ]]
[[ "$MCM_BASE" == "MCM-007" ]]
[[ "$R000_HELD_ACROSS_TURN" == "TRUE" ]]
[[ "$R000_RECUR_ON_EVERY_DELTA" == "TRUE" ]]
[[ "$R000_PRESENT_AT_READBACK" == "TRUE" ]]
[[ "$MULTI_SLOT_IS_MULTI_TIMELINE" == "FALSE" ]]
[[ "$MULTI_SLOT_IS_MULTI_POINTER" == "FALSE" ]]
[[ "$ALL_OLD_RUNTIME" == "FALSE" ]]
[[ "$OLD_ROOT_RUNTIME" == "FALSE" ]]

printf 'RUNTIME_N_PLUS=%s\n' "$RUNTIME_N_PLUS"
printf 'RUNTIME_SCHEMA=%s\n' "$RUNTIME_SCHEMA"
printf 'R000_CURRENT=%s\n' "$R000_CURRENT_CARRIER_DRIVE_ID"
printf '4D_CURRENT=%s/%s\n' "$FOUR_D_FOLDER_ID" "$MCM_CURRENT"
